import type { User, PurchaseOrder, MasterSKU, AuditLog, NotificationItem } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Admin User',
    email: 'admin@rlfood.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
    online: true,
    lastLogin: 'Just now',
    department: 'Procurement Management',
  },
  {
    id: 'usr-karim-1',
    name: 'Karim Purchaser',
    email: 'karim@rlfood.com',
    role: 'purchaser',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    online: true,
    lastLogin: '10 mins ago',
    department: 'Field Purchasing',
  },
  {
    id: 'usr-recv-1',
    name: 'Warehouse Receiver',
    email: 'warehouse@rlfood.com',
    role: 'receiver',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    online: true,
    lastLogin: '1 hour ago',
    department: 'Logistics & Receiving',
  },
  {
    id: 'usr-mgr-1',
    name: 'Sarah Ops Manager',
    email: 'sarah.ops@rlfood.com',
    role: 'manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    active: true,
    online: false,
    lastLogin: '3 hours ago',
    department: 'Executive Management',
  },
];

export const INITIAL_POS: PurchaseOrder[] = [
  {
    id: 'PO-2026-889',
    supplier: 'Metro Fresh Produce Ltd.',
    department: 'Central Kitchen',
    location: 'Main Facility #1',
    orderDate: '2026-07-29',
    deliveryDate: '2026-07-30',
    status: 'On Hold',
    receiveStatus: 'Pending',
    totalQuantity: 350,
    totalEstimatedCost: 1420.00,
    totalActualCost: 1420.00,
    createdByName: 'Admin User',
    createdById: 'usr-admin-1',
    notes: 'Urgent delivery required for weekend kitchen prep',
    items: [
      {
        id: 'item-101',
        sku: 'ING-TOM-01',
        name: 'Organic Tomatoes',
        category: 'Fresh Produce',
        orderedQty: 200,
        unit: 'kg',
        estimatedUnitPrice: 3.50,
        purchaseStatus: 'On Hold',
        receiveStatus: 'Pending',
        heldBy: 'Karim Purchaser',
        heldAt: '2026-07-29 14:20',
        notes: 'Locked by Karim while negotiating vendor discount',
      },
      {
        id: 'item-102',
        sku: 'ING-ONN-02',
        name: 'Red Onions',
        category: 'Fresh Produce',
        orderedQty: 150,
        unit: 'kg',
        estimatedUnitPrice: 4.80,
        purchasedQty: 150,
        actualUnitPrice: 4.80,
        purchaseStatus: 'Purchased',
        receiveStatus: 'Pending',
        purchasedAt: '2026-07-29 11:30',
        purchaserName: 'Karim Purchaser',
        receiptNumber: 'RCP-89211',
      },
    ],
  },
  {
    id: 'PO-2026-888',
    supplier: 'Apex Dairy & Poultry Supplies',
    department: 'Cold Storage Operations',
    location: 'North Logistics Hub',
    orderDate: '2026-07-29',
    deliveryDate: '2026-07-29',
    status: 'Purchased',
    receiveStatus: 'Partial Received',
    totalQuantity: 500,
    totalEstimatedCost: 3250.00,
    totalActualCost: 3200.00,
    createdByName: 'Sarah Ops Manager',
    createdById: 'usr-mgr-1',
    notes: 'Grade A inspected cold chain shipment',
    items: [
      {
        id: 'item-201',
        sku: 'DRY-CHK-01',
        name: 'Fresh Chicken Breast (Boneless)',
        category: 'Meat & Poultry',
        orderedQty: 300,
        unit: 'kg',
        estimatedUnitPrice: 8.50,
        purchasedQty: 300,
        actualUnitPrice: 8.40,
        receivedQty: 300,
        purchaseStatus: 'Purchased',
        receiveStatus: 'Received',
        purchasedAt: '2026-07-29 09:15',
        purchaserName: 'Karim Purchaser',
        receiptNumber: 'RCP-77209',
      },
      {
        id: 'item-202',
        sku: 'DRY-MLK-02',
        name: 'Whole Milk 3.2%',
        category: 'Dairy',
        orderedQty: 200,
        unit: 'Liters',
        estimatedUnitPrice: 3.50,
        purchasedQty: 200,
        actualUnitPrice: 3.40,
        receivedQty: 100,
        purchaseStatus: 'Purchased',
        receiveStatus: 'Partial Received',
        purchasedAt: '2026-07-29 09:15',
        purchaserName: 'Karim Purchaser',
        receiptNumber: 'RCP-77209',
        notes: '100 Liters backordered for tomorrow shipment',
      },
    ],
  },
  {
    id: 'PO-2026-887',
    supplier: 'Global Spice & Packaging Co.',
    department: 'Packaging & Assembly',
    location: 'Downtown Facility',
    orderDate: '2026-07-28',
    deliveryDate: '2026-07-28',
    status: 'Purchased',
    receiveStatus: 'Received',
    totalQuantity: 1200,
    totalEstimatedCost: 4890.00,
    totalActualCost: 4890.00,
    createdByName: 'Admin User',
    createdById: 'usr-admin-1',
    items: [
      {
        id: 'item-301',
        sku: 'PKG-BOX-01',
        name: 'Eco Meal Boxes 750ml',
        category: 'Packaging',
        orderedQty: 1000,
        unit: 'Pcs',
        estimatedUnitPrice: 3.80,
        purchasedQty: 1000,
        actualUnitPrice: 3.80,
        receivedQty: 1000,
        purchaseStatus: 'Purchased',
        receiveStatus: 'Received',
        purchasedAt: '2026-07-28 16:40',
        purchaserName: 'Karim Purchaser',
        receiptNumber: 'RCP-55310',
      },
      {
        id: 'item-302',
        sku: 'SPC-SLT-05',
        name: 'Himalayan Pink Salt (Fine)',
        category: 'Dry Goods & Spices',
        orderedQty: 200,
        unit: 'kg',
        estimatedUnitPrice: 5.45,
        purchasedQty: 200,
        actualUnitPrice: 5.45,
        receivedQty: 200,
        purchaseStatus: 'Purchased',
        receiveStatus: 'Received',
        purchasedAt: '2026-07-28 16:40',
        purchaserName: 'Karim Purchaser',
        receiptNumber: 'RCP-55310',
      },
    ],
  },
  {
    id: 'PO-2026-886',
    supplier: 'Golden Grains Wholesalers',
    department: 'Dry Storage',
    location: 'Main Facility #1',
    orderDate: '2026-07-29',
    deliveryDate: '2026-08-01',
    status: 'Pending',
    receiveStatus: 'Pending',
    totalQuantity: 800,
    totalEstimatedCost: 2600.00,
    totalActualCost: 0,
    createdByName: 'Admin User',
    createdById: 'usr-admin-1',
    items: [
      {
        id: 'item-401',
        sku: 'GRN-RIC-01',
        name: 'Basmati Long Grain Rice',
        category: 'Dry Goods & Spices',
        orderedQty: 500,
        unit: 'kg',
        estimatedUnitPrice: 4.20,
        purchaseStatus: 'Pending',
        receiveStatus: 'Pending',
      },
      {
        id: 'item-402',
        sku: 'GRN-FLR-02',
        name: 'All-Purpose Wheat Flour',
        category: 'Dry Goods & Spices',
        orderedQty: 300,
        unit: 'kg',
        estimatedUnitPrice: 1.66,
        purchaseStatus: 'Pending',
        receiveStatus: 'Pending',
      },
    ],
  },
];

export const INITIAL_SKUS: MasterSKU[] = [
  { id: 'sku-1', internalSKU: 'ING-TOM-01', supplierSKU: 'MTP-TOM-A', name: 'Organic Tomatoes', category: 'Fresh Produce', supplier: 'Metro Fresh Produce Ltd.', unit: 'kg', conversionFactor: 1.0, lastUpdated: '2026-07-25' },
  { id: 'sku-2', internalSKU: 'ING-ONN-02', supplierSKU: 'MTP-ONN-RED', name: 'Red Onions', category: 'Fresh Produce', supplier: 'Metro Fresh Produce Ltd.', unit: 'kg', conversionFactor: 1.0, lastUpdated: '2026-07-25' },
  { id: 'sku-3', internalSKU: 'DRY-CHK-01', supplierSKU: 'APX-CHK-BNL', name: 'Fresh Chicken Breast', category: 'Meat & Poultry', supplier: 'Apex Dairy & Poultry Supplies', unit: 'kg', conversionFactor: 1.0, lastUpdated: '2026-07-24' },
  { id: 'sku-4', internalSKU: 'DRY-MLK-02', supplierSKU: 'APX-MLK-32', name: 'Whole Milk 3.2%', category: 'Dairy', supplier: 'Apex Dairy & Poultry Supplies', unit: 'Liters', conversionFactor: 1.0, lastUpdated: '2026-07-26' },
  { id: 'sku-5', internalSKU: 'PKG-BOX-01', supplierSKU: 'GBL-BX-750', name: 'Eco Meal Boxes 750ml', category: 'Packaging', supplier: 'Global Spice & Packaging Co.', unit: 'Pcs', conversionFactor: 50, lastUpdated: '2026-07-20' },
];

export const INITIAL_LOGS: AuditLog[] = [
  { id: 'log-101', timestamp: '2026-07-29 14:20:05', action: 'PURCHASE_HOLD', details: 'Item ING-TOM-01 (Organic Tomatoes) placed on Hold Lock by Karim Purchaser', user: 'Karim Purchaser', role: 'purchaser' },
  { id: 'log-102', timestamp: '2026-07-29 11:30:12', action: 'PURCHASE_SAVE', details: 'Recorded purchase of 150kg Red Onions at $4.80/kg for PO-2026-889', user: 'Karim Purchaser', role: 'purchaser' },
  { id: 'log-103', timestamp: '2026-07-29 09:00:00', action: 'SYSTEM_SYNC', details: 'Google Sheets sync completed (4 orders, 8 items synced)', user: 'System AutoSync', role: 'admin' },
  { id: 'log-104', timestamp: '2026-07-28 16:40:22', action: 'WAREHOUSE_RECEIVE', details: 'Warehouse confirmed receive for PO-2026-887 (1000 Pcs Eco Meal Boxes)', user: 'Warehouse Receiver', role: 'receiver' },
  { id: 'log-105', timestamp: '2026-07-28 08:30:00', action: 'LOGIN', details: 'User Karim Purchaser logged in', user: 'Karim Purchaser', role: 'purchaser' },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  { id: 'notif-1', title: 'Item Lock Placed', message: 'Karim Purchaser locked Organic Tomatoes (PO-2026-889) for price negotiation.', timestamp: '10 mins ago', read: false, type: 'warning', source: 'system' },
  { id: 'notif-2', title: 'Warehouse Shipment Received', message: '1000 Pcs Eco Meal Boxes verified & received at Central Kitchen.', timestamp: '1 hour ago', read: false, type: 'success', source: 'system' },
  { id: 'notif-3', title: 'Telegram Dispatch Active', message: 'Automated daily purchasing summary pushed to executive Telegram channel.', timestamp: '2 hours ago', read: true, type: 'info', source: 'telegram' },
  { id: 'notif-4', title: 'Google Sheets Sync', message: 'Master worksheet synchronized with live cloud inventory sheet.', timestamp: '3 hours ago', read: true, type: 'info', source: 'sheets' },
];
